name: functional tests
on: pull_request
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: make

    - name: Test
      run: |
        mkdir /tmp/gw
        ./versitygw -a user -s pass posix /tmp/gw &
        sleep 1
        ./versitygw test -a user -s pass -e http://127.0.0.1:7070 full-flow
