name: general
on: pull_request
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Verify all files pass gofmt formatting
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then gofmt -s -d .; exit 1; fi

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -o versitygw cmd/versitygw/*.go

    - name: Test
      run: go test -v -timeout 30s -tags=github ./...

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash

    - name: Run govulncheck
      run: govulncheck ./...
      shell: bash