name: staticcheck
on: pull_request
jobs: 
  build: 
    name: Check
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
        id: go
      - 
        name: "Set up repo"
        uses: actions/checkout@v1
        with: 
          fetch-depth: 1
      - 
        name: "staticcheck"
        uses: dominikh/staticcheck-action@v1.3.0
        with: 
          install-go: false
