name: staticcheck
on: pull_request
jobs: 

  build: 
    name: Check
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
      id: go
 
    - name: "staticcheck"
      uses: dominikh/staticcheck-action@v1.3.0
      with: 
        install-go: false
