name: system tests
on: pull_request
jobs:
  build:
    name: RunTests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Run ShellCheck
        run: shellcheck -S warning ./tests/*.sh

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
        id: go

      - name: Get Dependencies
        run: |
          go get -v -t -d ./...

      - name: Install BATS
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core && ./install.sh $HOME

      - name: Build and run
        run: |
          make testbin
          export AWS_ACCESS_KEY_ID=user
          export AWS_SECRET_ACCESS_KEY=pass
          export AWS_REGION=us-east-1
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile versity
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile versity
          aws configure set aws_region $AWS_REGION --profile versity
          mkdir /tmp/gw
          export WORKSPACE=$GITHUB_WORKSPACE
          ./tests/run_all.sh
